include:
  - ./docker/database/docker-compose.yml
  - ./apps/tcg-api/docker-compose.yml
  - ./apps/cron/docker-compose.yml
  - ./apps/rest-api/docker-compose.yml
  - ./apps/graphql-api/docker-compose.yml
  - ./docker-compose.web.yml

networks:
  pika: